# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: twitterapp
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: twitterapp_test
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock


production:
  adapter: postgresql
  encoding: unicode
  database: twitterapp_production
  pool: 5
  password:
